### PR TITLE
#117 Default value for bookmark name when saving bookmark

### PR DESCRIPTION
**Pull request by KwanJunWen**
### Added

- Default value for bookmark name when request URL is not empty, otherwise fallback to original selected bookmark name.

### CODE REVIEW

**Comment by KwanJunWen** [comment]
#117

**Review by alexmario74 — COMMENTED** [review]
I think you should check if a name had been set from the user.
If it is you should use the name, and if it's not then you should use request method + url as default value for the bookmark name.

**Comment by mirkoperillo** [comment]
@KwanJunWen thank you for investing time in contributing to Resting and @alexmario74  thank you for your opinion.

Actually the solution of this issue is easier: I need to put information into the attribute `placeholder` of the `name` input field 

Here https://github.com/mirkoperillo/resting/blob/488742738bbd844010ee9e436fb75a0c418587a5/src/index.html#L222

The logic to show the default value ( method name + url) when the bookmark name isn't provided is already implemented
https://github.com/mirkoperillo/resting/blob/488742738bbd844010ee9e436fb75a0c418587a5/src/js/app/components/bookmarks/bookmarkVm.js#L34

**Comment by KwanJunWen** [comment]
Will make changes based on your comment, do I display an empty string when the request URL is not set?

For example:
Method: `GET`
URL: `undefined`
Rendered placeholder: `GET -`

**Comment by mirkoperillo** [comment]
@KwanJunWen LGTM.
Thank you to expose this edge case.
The best thing should be that a request with an empty url cannot be saved ( because the save button is disabled). 
But this is for another issue.

**Pull request merged**
