### PR TITLE
show progress bar to indicate request is sent but not yet received

### LINKED ISSUE #115: Progress indicator
## Expected Behavior

When you send a request to a remote server, sometimes takes more than 1 second, so an actual progress indicator that request is fired and we are waiting for an answer from remote server is needed.

## Actual Behavior

When you make a request, if this takes some times, you don't know what is going on

## Steps to Reproduce the Problem

  1. make a request to a slow serve
  1. wait for answer
  1. do it again

## Specifications

  - Addon Version: 1.0.3
  - Firefox Version: 80.0.1
  - OS: Windows 10

### PR DESCRIPTION
**Pull request by luisgregson**
Fixes #115 

Bar animates when a request is sent.

image

### CODE REVIEW

**Comment by mirkoperillo** [comment]
@luisgregson it seems a good start.
I propose you a couple of changes.
1. Move the progress bar under the url input field
edit-screen
2. The progress bar should appear when a request starts and disappear when the request ends

I'm available to talk about this

**Comment by luisgregson** [comment]
> @luisgregson it seems a good start.
> I propose you a couple of changes.
> 
> 1. Move the progress bar under the url input field
>    edit-screen
> 2. The progress bar should appear when a request starts and disappear when the request ends
> 
> I'm available to talk about this

Thanks for the feedback
1. No problem. I'll move ot

**Comment by luisgregson** [comment]
> @luisgregson it seems a good start.
> I propose you a couple of changes.
> 
> 1. Move the progress bar under the url input field
>    edit-screen
> 2. The progress bar should appear when a request starts and disappear when the request ends
> 
> I'm available to talk about this

Sorry, accidentally, hit the "Close with comment" button.

1. No problem, I'll move it.
2. I initially had the bar hidden when there's no pending request, but it was really jarring for requests that respond quickly as you just see it flash up and can't really tell what it was. How about having the progress bar unfilled until the first request is sent?

**Comment by mirkoperillo** [comment]
> How about having the progress bar unfilled until the first request is sent?

@luisgregson  why not, I can be a possibility.

**Comment by luisgregson** [comment]
I've moved the bar and set the progress to 0.01% before the first request is sent (0 would set the width to 0 which is bad for accessibility)

I think it looks great now, but let me know if you have any more feedback

**Comment by mirkoperillo** [comment]
@luisgregson LGTM.
Good work. I merge it immediately.
Thank you for contributing to Resting

**Pull request merged**
