### PR TITLE
fix for issue #104

### PR DESCRIPTION
**Pull request by alexmario74**
I removed the code mentioned in the issue that was supposed to centered the dialogs.

The reason for this is because that code, if it worked, it did just at the beginning.

So if a user will change the size of the window, the dialogs where not centered properly.

The code was also not working properly as explained in the issue #104.

So I opted for a full css solution, that should do the job in a better and performant way.

I haven't tested on MacOS as I don't have the development environment there, so this is just tested on Windows.

### CODE REVIEW

**Comment by mirkoperillo** [comment]
@alexmario74 thank you for the contribution, I'll give it a look as soon at possible

**Comment by mirkoperillo** [comment]
Hi @alexmario74,

I tested the fix, but I have a problem.
It seems that the dialogs opened by the buttons in the bookmarks panel have a wrong behaviour. 
The screen in attachment is more clear about.

The bookmark panel is a component and it seems that the browser considers the component dimension for the calculation of the position of dialogs present in that dialog.
( I'm not sure about that, it's only an impression).

Resting  -screen

**Comment by alexmario74** [comment]
You where right, I forgot that dialog.

I fixed with a new commit, please check.

**Comment by alexmario74** [comment]
I think my previous fix was not good, I found out that it could be done much easely with just a bit of css.

And that can be done directly on the dialog class.

Now it looks fine for me.

**Comment by mirkoperillo** [comment]
@alexmario74 thank you a lot. This solution is optimal

**Pull request merged**
