### PR TITLE
Run prettier formatter through entire repo

### LINKED ISSUE #187: Format codebase
Currently code in many places is not formatted properly. I am having to disable `Format on save` on my editor to push any PRs for review. Also code not being formatted causes trouble in skimming through it.

Can we resolve this? Maybe by running a formatter like prettier on entire codebase in one PR? Or by fixing one file at a time when we make some changes?

### PR DESCRIPTION
**Pull request by nikhilraojl**
Ignored:
- *.min.css
- src/js/require.js
- src/js/vendor/*

Closes #187

### CODE REVIEW

**Comment by nikhilraojl** [comment]
Can ignore additional files if preferred.

**Comment by mirkoperillo** [comment]
@nikhilraojl I have to ask you some improvements:
* please ignore `css/styles/*`. This is a third party folder used by highlight library
* is it possible to remove `;` at the end of all js instructions ?
* is it possible to prefer single quote `'` instead of double quote `"` ?
* Can you provide the prettier config are you using ?
* Can you improve README for the prettier installation and usage ?
* I don't like too much how `<a>` is formatted here https://github.com/mirkoperillo/resting/pull/189/files#r1206747282

Thank you so much for your help, I very appreciate it.

**Comment by nikhilraojl** [comment]
@alexmario74 
- Ignored all `src/css/*` except `src/css/resting.css`
- Trailing `;` are removed
- Switch to single quotes `'` from double quotes `"`
- Committed `.prettierrc` the config file and `.prettierignore` files
- Improved `<a>` like formatting from the earlier change

I am not sure where to add README instructions so I wrote them below. Please suggest changes and where to include the instructions.

Instructions for vscode(These options should be similar if you are using a different editor)
1. This project uses `prettier` for code formatting, kindly run this formatter before pushing any changes
2. To run the formatter, install the `prettier` extension and set it as default formatter
3. Now use manual `format document with` option or turn on `format on save` option to automatically format files when saved
4. Alternatively, install `prettier cli` ([instructions here](https://prettier.io/docs/en/cli.html)) and use command `prettier --write src` to format files with single command

**Comment by mirkoperillo** [comment]
@nikhilraojl good work 

> I am not sure where to add README instructions so I wrote them below. Please suggest changes and where to include the instructions.

I think a good place could be Project Setup section of https://github.com/mirkoperillo/resting/blob/master/CONTRIBUTING.md

**Comment by nikhilraojl** [comment]
> I think a good place could be Project Setup section of https://github.com/mirkoperillo/resting/blob/master/CONTRIBUTING.md

Updated `CONTRIBUTING.md`

**Pull request merged**
